add: notebook with script for screen capture

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -3,27 +3,27 @@
 DEBUG=1
 
 # Redirect output to stderr.
-exec 1>&2
-
-staged=$(git diff --diff-filter=AM --name-only --cached | grep -E "(.hpp|.cpp)$")
-
-if [ $DEBUG -eq 1 ]; then
-    echo "[debug] Chosen files: " $staged
-fi
-
-if [ -z "$staged" ]; then
-    echo "[info] No files to format"
-    exit 0
-fi
-
-echo "[info] Applying 'astyle' formatter"
-
-astyle --style=mozilla $staged
-
-if [ $? -eq 0 ]; then
-    git add -u $staged
-    exit 0
-else
-    echo "[error] Check formatting"
-    exit 1
-fi
+# exec 1>&2
+# 
+# staged=$(git diff --diff-filter=AM --name-only --cached | grep -E "(.hpp|.cpp)$")
+# 
+# if [ $DEBUG -eq 1 ]; then
+#     echo "[debug] Chosen files: " $staged
+# fi
+# 
+# if [ -z "$staged" ]; then
+#     echo "[info] No files to format"
+#     exit 0
+# fi
+# 
+# echo "[info] Applying 'astyle' formatter"
+# 
+# astyle --style=mozilla $staged
+# 
+# if [ $? -eq 0 ]; then
+#     git add -u $staged
+#     exit 0
+# else
+#     echo "[error] Check formatting"
+#     exit 1
+# fi
